### ISSUE TITLE
endToEndTest does not compile on Windows

### ISSUE THREAD

**Issue by SeventhOfNine** [gameontext/gameon-map#106]
There are 100 errors reported, here are some of them:

gameon\map\map-app\src\endToEnd\java\org\gameontext\map\TestRoomCreate.java:3: error: package org.junit does not exist
import static org.junit.Assert.assertTrue;
gameon\map\map-app\src\endToEnd\java\org\gameontext\map\TestRoomCreate.java:9: error: package javax.ws.rs.client does not exist
import javax.ws.rs.client.Client;
gameon\map\map-app\src\endToEnd\java\org\gameontext\map\TestRoomSwap.java:37: error: package org.apache.http does not exist
import org.apache.http.HttpResponse;
gameon\map\map-app\src\endToEnd\java\org\gameontext\map\TestRoomCreate.java:17: error: package org.gameontext.map.model does not exist
import org.gameontext.map.model.ConnectionDetails;

**Comment by SeventhOfNine** [comment]
If you change the gradle build file as shown below, the code will compile OK.

But then the tests appear not to run (only TestCreateRoom is enabled, the other one is @Ignore'd) because it's expecting a server to be running.
...
// setup for end-2-end tests, needs to be in this order
sourceSets {
  endToEndTest {
    java.srcDir file('/src/endToEnd/java')
    resources.srcDir file('/src/endToEnd/resources')
  }
}

dependencies {
  endToEndTestCompile sourceSets.main.output
  endToEndTestCompile sourceSets.test.output 

  endToEndTestCompile configurations.compile
  endToEndTestCompile configurations.testCompile 

  endToEndTestRuntime configurations.runtime
  endToEndTestRuntime configurations.testRuntime 
}

task endToEndTest(type: Test) {
  testClassesDir = sourceSets.endToEndTest.output.classesDir
  classpath = sourceSets.endToEndTest.runtimeClasspath
}
// end setup for end-2-end tests
...

**Comment by SeventhOfNine** [comment]
Error from TestCreateRoom:
javax.ws.rs.ProcessingException: java.net.ConnectException: ConnectException invoking http://127.0.0.1:9099/map/v1/sites: Connection refused: connect
	at org.apache.cxf.jaxrs.client.AbstractClient.checkClientException(AbstractClient.java:569)
	at org.apache.cxf.jaxrs.client.AbstractClient.preProcessResult(AbstractClient.java:551)
	at org.apache.cxf.jaxrs.client.WebClient.doResponse(WebClient.java:1142)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1092)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:894)
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:865)
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:428)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1636)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.method(WebClient.java:1631)
	at org.apache.cxf.jaxrs.client.WebClient$SyncInvokerImpl.post(WebClient.java:1571)
	at org.apache.cxf.jaxrs.client.spec.InvocationBuilderImpl.post(InvocationBuilderImpl.java:145)
	at org.gameontext.map.TestRoomCreate.createRoom(TestRoomCreate.java:76)
	at org.gameontext.map.TestRoomCreate.testcreateRooms(TestRoomCreate.java:56)

**Comment by BarDweller** [comment]
I'm not sure this is running on Linux either.. tho it doesn't fail to compile, gradle always seems to think the dir is 'UP-TO-DATE' even when run with --rerun-tasks etc. 
testRoomCreate seems to be active in the source, but definitely would require a running server, and I can't see where one is ever supposed to be started.
