### ISSUE TITLE
Kafka failed to initialize

### ISSUE THREAD

**Issue by ebullient** [gameontext/gameon-map#111]
```
[8/30/18 3:18:34:639 UTC] 00000024 id=         net.wasdev.gameon.map                                        E Kafka(-95978821): Unknown error during kafka init, please report 
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:342)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:191)
	at org.gameontext.map.kafka.Kafka.init(Kafka.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:97)
	at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:80)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:122)
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:162)
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:99)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125)
	at org.gameontext.map.kafka.Kafka$Proxy$_$$_WeldClientProxy.subscribe(Unknown Source)
	at org.gameontext.map.auth.PlayerClient.init(PlayerClient.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

```
Caused by: org.apache.kafka.common.KafkaException: javax.security.auth.login.LoginException: java.lang.IllegalArgumentException: CWWKS1108E: WSLoginModuleProxy delegate option is not set.
	at com.ibm.ws.security.jaas.common.modules.WSLoginModuleProxy.initialize(WSLoginModuleProxy.java:85)
	at com.ibm.ws.kernel.boot.security.LoginModuleProxy.initialize(LoginModuleProxy.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:774)
	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:196)
	at javax.security.auth.login.LoginContext$5.run(LoginContext.java:721)
	at javax.security.auth.login.LoginContext$5.run(LoginContext.java:719)
	at java.security.AccessController.doPrivileged(AccessController.java:732)
	at javax.security.auth.login.LoginContext.invokeCreatorPriv(LoginContext.java:719)
	at javax.security.auth.login.LoginContext.login(LoginContext.java:593)
	at org.apache.kafka.common.security.authenticator.AbstractLogin.login(AbstractLogin.java:58)
	at org.apache.kafka.common.security.kerberos.KerberosLogin.login(KerberosLogin.java:109)
	at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:55)
	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:89)

```

**Comment by ebullient** [comment]
Fixed by 638899730784964d0897ef5b7dd174e17edf1a79
